name: prefs_config
description: Dart Plugin for generating Settings/Preference screen for Flutter.
version: 0.8.1
author: Gaddo F Benedetti <gaddo@gfb-consulting.com>
homepage: https://github.com/gaddobenedetti/prefs_config

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
