name: prefs_config
description: Dart Plugin for generating Settings/Preference screen for Flutter.
version: 0.9.0
homepage: https://github.com/gaddobenedetti/prefs_config

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
